[project]
name = "salsah-2"
version = "0.1.0"
description = ""
authors = [
    {name = "Lukas Rosenthaler",email = "lukas.rosenthaler@unibas.ch"}
]
readme = "README.md"
requires-python = "^3.14"
dependencies = [
    "oldap-tools (>=0.3.11,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
